# Generated by Django 3.2.19 on 2023-06-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_shoppinglistitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_items', to='shoppinglist.shoppinglist'),
        ),
    ]
