# Generated by Django 3.2.19 on 2023-06-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0004_alter_shoppinglistitem_shopping_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='owner',
        ),
    ]
