# Generated by Django 3.2.19 on 2023-06-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0006_shoppinglistitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='items',
            field=models.ManyToManyField(through='shoppinglist.ShoppingListItem', to='shoppinglist.ShoppingList'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.shoppinglist'),
        ),
    ]
