# Generated by Django 3.2.19 on 2023-06-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0007_auto_20230608_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='items',
        ),
    ]
