# Generated by Django 3.2.19 on 2023-06-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0008_remove_shoppinglist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='item',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
    ]
