# Generated by Django 3.2.19 on 2023-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0009_auto_20230608_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='item',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='quantity',
            field=models.JSONField(default=list),
        ),
    ]
