# Generated by Django 3.2.19 on 2023-06-09 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppinglist', '0012_auto_20230609_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='item',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shoppinglist.shoppinglist'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
