# Generated by Django 3.2.19 on 2023-06-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='../default_upload_wck8zz', upload_to='images/'),
        ),
    ]
