# Generated by Django 3.2.19 on 2023-06-07 12:54

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('due_date'), nulls_last=True)]},
        ),
    ]
