# Generated by Django 3.2.19 on 2023-06-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20230527_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='planted',
            new_name='planted_at',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='perennial',
        ),
    ]
