# Generated by Django 3.2.19 on 2023-06-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20230605_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('berry_bush', 'Berry bush'), ('herb', 'Herb'), ('bulb', 'Bulb'), ('cacti', 'Cacti'), ('fern', 'Fern'), ('grass', 'Grass'), ('shrub', 'Shrub'), ('tree', 'Tree'), ('annual', 'Annual'), ('biennial', 'Biennial'), ('perennial', 'Perennial'), ('vegetable', 'Vegetable'), ('fruit_tree', 'Fruit tree'), ('succulent', 'Succulent')], default='unknown', max_length=255, null=True),
        ),
    ]
